/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DemosRouteImport } from './routes/demos'
import { Route as ExperimentRouteImport } from './routes/experiment'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiIdRouteImport } from './routes/api.$id'
import { Route as DemosIdRouteImport } from './routes/demos_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentRoute = ExperimentRouteImport.update({
  id: '/experiment',
  path: '/experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdRoute = ApiIdRouteImport.update({
  id: '/api/$id',
  path: '/api/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosIdRoute = DemosIdRouteImport.update({
  id: '/demos_/$id',
  path: '/demos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/demos': typeof DemosRoute
  '/experiment': typeof ExperimentRoute
  '/terms': typeof TermsRoute
  '/api/$id': typeof ApiIdRoute
  '/demos/$id': typeof DemosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/demos': typeof DemosRoute
  '/experiment': typeof ExperimentRoute
  '/terms': typeof TermsRoute
  '/api/$id': typeof ApiIdRoute
  '/demos/$id': typeof DemosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/demos': typeof DemosRoute
  '/experiment': typeof ExperimentRoute
  '/terms': typeof TermsRoute
  '/api/$id': typeof ApiIdRoute
  '/demos_/$id': typeof DemosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/demos'
    | '/experiment'
    | '/terms'
    | '/api/$id'
    | '/demos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/demos'
    | '/experiment'
    | '/terms'
    | '/api/$id'
    | '/demos/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/demos'
    | '/experiment'
    | '/terms'
    | '/api/$id'
    | '/demos_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  DemosRoute: typeof DemosRoute
  ExperimentRoute: typeof ExperimentRoute
  TermsRoute: typeof TermsRoute
  ApiIdRoute: typeof ApiIdRoute
  DemosIdRoute: typeof DemosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment': {
      id: '/experiment'
      path: '/experiment'
      fullPath: '/experiment'
      preLoaderRoute: typeof ExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$id': {
      id: '/api/$id'
      path: '/api/$id'
      fullPath: '/api/$id'
      preLoaderRoute: typeof ApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos_/$id': {
      id: '/demos_/$id'
      path: '/demos/$id'
      fullPath: '/demos/$id'
      preLoaderRoute: typeof DemosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  DemosRoute: DemosRoute,
  ExperimentRoute: ExperimentRoute,
  TermsRoute: TermsRoute,
  ApiIdRoute: ApiIdRoute,
  DemosIdRoute: DemosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
